# Chapter 5 - Advanced topics on handling collections 
## This chapter covers
* Vectorizing your code, aka broadcasting
* Understanding subtyping rules for parametric types
* Integrating Julia with Python
* Performing t-SNE dimensionality reduction

## Broadcasting!
Broadcasting is another way to 'broadcast' a function to a set of elements, to iterate over a collection, the way a map() function, or comprehension loop would. 

A very basic example - multiple every element of x with every element of y, index wise, meaning element of index 1 in x is multiplied with element of index 1 in y. 

In [1]:
x = [2, 3, 4] ; y = [2, 3, 4]

3-element Vector{Int64}:
 2
 3
 4

The "." dot operator is the magic symbol of broadcasting

In [2]:
x .* y 

3-element Vector{Int64}:
  4
  9
 16

The same thing can be achieved with **map()** and **comprehension** 

In [3]:
map(*, x, y)

3-element Vector{Int64}:
  4
  9
 16

Comprehension is much uglier in my opinion

In [5]:
[x[i] * y[i] for i in eachindex(x,y)] # peep the eachindex() function which listed the index size 

3-element Vector{Int64}:
  4
  9
 16

**If the sizes of a and b do not match, we get an error**

### Breaking the index equivalence rule whereby both collections must be of equal size to perform broadcasting 
There is one exception to the rule that dimensions of all collections taking part in broadcasting must match. This exception states that single-element dimensions get expanded to match the size of the other collection by repeating the value stored in this single element: If the second collection **ONLY** has a single element, than iteration is possible on this. 

In [6]:
x .* [2]

3-element Vector{Int64}:
 4
 6
 8

### Another example using matrices 

In [7]:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] .* [1 2 3 4 5 6 7 8 9 10]

10×10 Matrix{Int64}:
  1   2   3   4   5   6   7   8   9   10
  2   4   6   8  10  12  14  16  18   20
  3   6   9  12  15  18  21  24  27   30
  4   8  12  16  20  24  28  32  36   40
  5  10  15  20  25  30  35  40  45   50
  6  12  18  24  30  36  42  48  54   60
  7  14  21  28  35  42  49  56  63   70
  8  16  24  32  40  48  56  64  72   80
  9  18  27  36  45  54  63  72  81   90
 10  20  30  40  50  60  70  80  90  100

"This technique is often used in practice to get a Cartesian product of all inputs. For instance, in part 2, you will learn that when you write "x" => sum in DataFrames.jl, you ask the package to apply the sum function to the column x of the data frame. A common scenario is that we want to apply several functions to several columns of a data frame. Using broadcasting, this can be written concisely as follows:"

In [8]:
["x", "y"] .=> [sum minimum maximum]

2×3 Matrix{Pair{String}}:
 "x"=>sum  "x"=>minimum  "x"=>maximum
 "y"=>sum  "y"=>minimum  "y"=>maximum

recall that vectors in Julia are columnar; in this case, the vector has one column and two rows), and the [sum minimum maximum] expression creates a matrix with one row and three columns. More from this blog post https://julialang.org/blog/2013/09/fast-numeric/ 

**"Julia arrays are stored in column-major order, which means that the rows of a column are contiguous, but the columns of a row are generally not. It is therefore generally more efficient to access data column-by-column than row-by-row."**

### Some nice example of using broadcasting with functions 
If we want to prefix 22 values with a certain element, say "chr", we can do 

In [9]:
string.("chr", 1:22) 

22-element Vector{String}:
 "chr1"
 "chr2"
 "chr3"
 "chr4"
 "chr5"
 "chr6"
 "chr7"
 "chr8"
 "chr9"
 "chr10"
 "chr11"
 "chr12"
 "chr13"
 "chr14"
 "chr15"
 "chr16"
 "chr17"
 "chr18"
 "chr19"
 "chr20"
 "chr21"
 "chr22"

In [10]:
f(i::Int) = string("got integer ", i) ; f(s::String) = string("got string ", s) 

f (generic function with 2 methods)

In [11]:
f.([1, "1"]) 

2-element Vector{String}:
 "got integer 1"
 "got string 1"

## Protecting collections from being broadcasted over
Let's say we have a vector of values, any we want to know whether any of the values are in another collection, what ought we do? We could try use the **in()** function? 

In [12]:
in([1, 3, 5, 7, 9], [1, 2, 3, 4]) 

false

But that doesn't work even though 1 and 3 are matches, so what's the reason? The first array is treated as a whole, and so ALL the elements must be matching between the arrays. What if we wrap the second array in two brackets? 

In [13]:
in([1, 3, 5, 7, 9], [[1, 2, 3, 4]])

false

Nope, still treated as a whole. Let's try using the function where we know all elements are matching. in([1, 3, 5, 7, 9], [1, 2, 3, 4, [1, 3, 5, 7, 9]])

In [14]:
in([1, 3, 5, 7, 9], [1, 2, 3, 4, [1, 3, 5, 7, 9]]) 

true

This still didn't solve our original problem, whereby we want to know if and which ANY of the elements in the first set are in the second. What if we use broadcasting? 

In [15]:
in.([1, 3, 5, 7, 9], [1, 2, 3, 4])

LoadError: DimensionMismatch: arrays could not be broadcast to a common size; got a dimension with lengths 5 and 4

Nope. Hmmmm. 

Well we know that using the set operations should work, let's perform an intersection. 

In [16]:
intersect([1, 3, 5, 7, 9], [1, 2, 3, 4]) 

2-element Vector{Int64}:
 1
 3

As expected, but, there is another way to still use the **in()** function.    

"How should we resolve this issue? The solution is to wrap the vector that we want to be reused as a whole with Ref. In this way, we will protect this object from being iterated over. Instead, it will be unwrapped from Ref and treated by broadcasting as if it were a scalar, and thus this value will be repeated to match the dimension of the other container:" 

In [17]:
in.([1, 3, 5, 7, 9], Ref([1, 2, 3, 4]))

5-element BitVector:
 1
 1
 0
 0
 0

Now it works, I suppose.. 

### wtf is Ref?

Ref can be seen as shorthand for "Reference" - it takes the values of a collection, and creats a single value reference of the value, which it stores in an array, almost like a little iterator of it's own. So when we run broadcasting in combination with **Ref()**, Ref will operator on each element of the array, and thus the size of the first and second arrays will be equal (1 each), allowing for the broadcasting to work as intended.... a bit random but hey this is effective. 

## Exercise 5.1 
The parse function can be used to convert a string into a number. For instance, if you want to parse a string as an integer, write parse(Int, "10") to get the integer 10. Assume you are given a vector of strings ["1", "2", "3"]. Your task is to create a vector of integers by parsing the strings contained in the given vector.

In [23]:
string_vec = ["1", "2", "3"] 

3-element Vector{String}:
 "1"
 "2"
 "3"

In [24]:
int_vec = parse.(Int, string_vec)

3-element Vector{Int64}:
 1
 2
 3

## Analyzing Anscombe's quartet data using broadcasting

aq = [10.0   8.04  10.0  9.14  10.0   7.46   8.0   6.58
             8.0   6.95   8.0  8.14   8.0   6.77   8.0   5.76
            13.0   7.58  13.0  8.74  13.0  12.74   8.0   7.71
             9.0   8.81   9.0  8.77   9.0   7.11   8.0   8.84
            11.0   8.33  11.0  9.26  11.0   7.81   8.0   8.47
            14.0   9.96  14.0  8.1   14.0   8.84   8.0   7.04
             6.0   7.24   6.0  6.13   6.0   6.08   8.0   5.25
             4.0   4.26   4.0  3.1    4.0   5.39  19.0  12.50
            12.0  10.84  12.0  9.13  12.0   8.15   8.0   5.56
             7.0   4.82   7.0  7.26   7.0   6.42   8.0   7.91
             5.0   5.68   5.0  4.74   5.0   5.73   8.0   6.89]

In [8]:
using Pkg

In [9]:
Pkg.add("Statistics") ; using Statistics

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


Calculate the mean of each column in the matrix, using broadcasting of the mean function combined with the eachcol() function

In [10]:
mean.(eachcol(aq)) 

8-element Vector{Float64}:
 9.0
 7.500909090909093
 9.0
 7.500909090909091
 9.0
 7.500000000000001
 9.0
 7.50090909090909

If we don't use broadcasting, we get a row based estimate 

In [11]:
mean(eachcol(aq))

11-element Vector{Float64}:
  8.6525
  7.4525
 10.47125
  8.56625
  9.35875
 10.492500000000001
  6.3375
  7.03125
  9.71
  6.92625
  5.755000000000001

We'll just show a brief comparison between the correlation function from chapter 4, and an updated correlation function which no incorporates broadcasting. 

In [12]:
function R²(x, y)
   X = [ones(11) x]
   model = X \ y
   prediction = X * model
   error = y - prediction
   SS_res = sum(v -> v ^ 2, error)
   mean_y = mean(y)
   SS_tot = sum(v -> (v - mean_y) ^ 2, y)
   return 1 - SS_res / SS_tot
end

R² (generic function with 1 method)

Pay attention to the slight differences and the streamlining it allows 

In [13]:
function R²(x, y)
   X = [ones(11) x]
   model = X \ y
   prediction = X * model
   SS_res = sum((y .- prediction) .^ 2)
   SS_tot = sum((y .- mean(y)) .^ 2)
   return 1 - SS_res / SS_tot
end

R² (generic function with 1 method)

**"By now you know four ways of iteratively applying operations to elements of collections:**

   * Using for loops
   * Using comprehensions
   * Using the map function (and other similar higher-order functions that take functions as their arguments)
   * Using broadcasting

**You’re probably asking yourself in which cases you should use which option. Fortunately, this is mostly a matter of convenience and code readability. In your projects, use the option that is easiest for you to use and that results in the most readable code. One of the great features of Julia is that all these options are fast. Most of the time, you won’t sacrifice performance by choosing one over the other."**

Another brief reminder of comprehension - much more can be done ofcourse 

In [17]:
[sum(x) for x in [[1,2,3]]] 

1-element Vector{Int64}:
 6

## Defining collections with parametric types

When we're at the stage where we are ready to start defining completely new, custom methods for our work, and understanding of the Types which our methods accept is a foundational key. Does it work on Intergers? All Intergers or only 8bit? Can it also work if the user accidently plugs in a Float with a single zero digit? Does it take vectors, dicts etc.? What are the parameters for our methods. 

A simple demonstration in which we create a vector holding float values - even though we provide intergers, they are automatically parsed to floats. 

In [34]:
float_vec = Float64[1,2,3]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

If we want a dict in which the keys are UInt8 (8bit unicode interger) and the values are Float64, we can define this immedietly after the **Dict** term

In [33]:
Dict{UInt8, Float64}(0 => 0, 1 => 1) 

Dict{UInt8, Float64} with 2 entries:
  0x00 => 0.0
  0x01 => 1.0

### The eltype function 
The function **eltype** will tell us the type of elements/values that a **collection** can store - perhaps it's an array only storing floats, or a Tuple storing everything and so on and so on.... 

In [35]:
eltype(float_vec)

Float64

This is the cousin to the **typeof()** function which works on the entire collection and gives us a bit more information 

In [37]:
typeof(float_vec)

Vector{Float64} (alias for Array{Float64, 1})

### Nuances of types and subtyping
Typing our methods in the correct fashion is essential if we want to avoid naive errors - and by naive I mean using a Type which is almost correct, but just slightly off the mark - for instance, naively restricting our method types to Strings, without really having a reason to, when it's likely better suited to AbstractString, which allows us to input SubStrings, which look identical to Strings in the first place. Or perhaps we want type stability but we aren't restrictive enough in our definition.   

Getting a firm grip on the way Julia handles typing is thus always fruitful for us.    

Things can definitely get tricky, here is an example of using a collection which is an AbstractVector{Int} into a method which takes AbstractVector{Real}, simply assuming that since Int is a subtype of Real numbers, than by extension AbstractVector{Int} is also likely a subtype of AbstractVector{Real} -- but this isn't the case! 

In [38]:
isa([1,2,3], AbstractVector{Int}) 

true

In [61]:
isa([1,2,3], AbstractVector{Real}) 

false

Let's take a look at the all the subtypes of AbstractVector{Real} 

In [62]:
subtypes(AbstractVector{Int})

16-element Vector{Any}:
 AbstractRange{Int64}
 AbstractSlices{Int64, 1}
 Base.LogicalIndex{Int64}
 Base.ReinterpretArray{Int64, 1, S} where S
 Base.ReshapedArray{Int64, 1}
 Base.Sort.WithoutMissingVector{Int64}
 Core.Compiler.AbstractRange{Int64}
 Core.Compiler.LinearIndices{1, R} where R<:Tuple{Core.Compiler.AbstractUnitRange{Int64}}
 Core.Compiler.TwoPhaseVectorView
 DenseVector{Int64} (alias for DenseArray{Int64, 1})
 LinearIndices{1, R} where R<:Tuple{AbstractUnitRange{Int64}}
 PermutedDimsArray{Int64, 1}
 AbstractSparseVector{Int64} (alias for SparseArrays.AbstractSparseArray{Int64, Ti, 1} where Ti)
 SparseArrays.ColumnIndices{Int64, S} where S<:(SparseArrays.AbstractSparseMatrixCSC{<:Any, Int64})
 SparseArrays.ReadOnly{Int64, 1, V} where V<:AbstractVector{Int64}
 SubArray{Int64, 1}

In [63]:
supertypes(AbstractVector{Real})

(AbstractVector{Real}, Any)

When defining our collections and methods, we can specify the types of elements that it is allowed to store/contain - in the following case we want to create an AbstractVector which stores elements of the Real type

In [66]:
q = AbstractVector{<:Real}

AbstractVector{<:Real} (alias for AbstractArray{<:Real, 1})

If we create an AbstractVector of the type Int, we won't be able to house anything but elements of this type inside of it 

**"Vector{Int} is not a subtype of Vector{Real}. This is because both Vector{Int} and Vector{Real}, as you have seen in this section, can have instances. One is a container that can store only integers. The other is a container that can store any Real values. These are two concrete and different containers. Neither is a subtype of the other."** 

### Using subtyping rules to define functions 
Some fun!!!!

In [69]:
function ourcov(x::AbstractVector{<:Real},
                       y::AbstractVector{<:Real})
           len = length(x)
           @assert len == length(y) > 0
           return sum((x .- mean(x)) .* (y .- mean(y))) / (len - 1)
end 

ourcov (generic function with 1 method)

In [70]:
ourcov(1:4, [1.0, 3.0, 2.0, 4.0]) 

1.3333333333333333

We can see that so long as we provide arguments to the function which are of the correct type, we should be OK. What happens if we provide an argument of an incorrect type, which *seems* to look OK but in fact isn't? 

"Note that in the code, we mix a range of integers with a vector of floating-point values, and they get accepted and are handled correctly. However, if we pass a collection whose element type is not a subtype of Real, the function will fail, even if we do not change the specific values stored by the collection:" 

In [71]:
ourcov(1:4, Any[1.0, 3.0, 2.0, 4.0])

LoadError: MethodError: no method matching ourcov(::UnitRange{Int64}, ::Vector{Any})

Closest candidates are:
  ourcov(::AbstractVector{<:Real}, ::AbstractVector{<:Real})
   @ Main In[69]:1


This fails as Any is not a subtype of Real, in fact, Real is a Subtype of Any.  

In [74]:
typejoin(Int, Float64)

Real

In [75]:
typeof([1,2,3])

Vector{Int64} (alias for Array{Int64, 1})

### Determing the Type our methods should used based upon the collection at hand
If we have a sample collection of elements which will serve as a reference for our methods/functions, we can determine the Type of the collection by broadcasting the **identity()** function over our collection

In [76]:
identity.([1.0, 1])

2-element Vector{Float64}:
 1.0
 1.0

In [77]:
identity.(Any[1.0, 1])

2-element Vector{Real}:
 1.0
 1

In the beginning there was use-value... no doubt. 

In capitalism, the use-value of items, objects and all manner of articles of life are abstracted to their exchange-form, given they are dominated by capital owners, for the end of profit. This foundational feature of capitalism, whereby distribution of articles for life are conquered and entrusted to profit-seeking firms, produces the impetus to amplify the *perceived* use-value of an item, thus balooning it's potential exchange value. 

Through an long history of mediums, this image of use-value has been 
Engineered obsolescence, the production of low-quality items, the domination of advertising spheres, whereby the power to advertise is a direct extension from the extraction of profit - cyclicality, 


Wolgang's work is a remarkable exploration of the transformations that use-value and exchange-value, the illusions and mystification's which occur - their sexual guises and seductions, and their modification of social behavior and it's downstream anthropological manifestations -

Capital has the power to change us far more than we change it. changes us far more than