# Week 2 Notes - Getting and Cleaning Data

## Reading from MySQL
Data in SQL are structured into databases -> databases consist of tables with fields -> tables contain entries as rows. The tables themselves often represent specific aspects of the data which are interlinked within the database - say a table for the salaries of employees, another of the annnual leave, another table for their personal details and so on. 

## Let's install MySQL
In R `install.packages("RMySQL")` 

In julia

In [1]:
using Pkg; Pkg.add("MySQL") ; using MySQL

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


In [2]:
Pkg.add("DataFrames") ; using DataFrames  

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


## Connecting to databases - UCSC genome browser example

Connecting to the UCSC MySQL server and pulling the databases on UCSC that are available to us -- let's do it in R. This will establish a connection to the server - a stream, and then using this stream we will execute a MySQL command `show databases;` to retrieve the available databases, and then disconnect from the stream. 
```R
ucscDB <- dbConnect(MySQL(), user="genome", host="genome-mysql.cse.ucsc.edu")  
result <- dbGetQuery(ucscDB, "show databases;"); dbDisconnect(ucscDB);
```

In Julia we can do this by employing the MySQL.jl package - part of the Databases.jl family;

In [3]:
# Connecting https://mysql.juliadatabases.org/dev/
ucscDB = DBInterface.connect(MySQL.Connection, "genome-mysql.soe.ucsc.edu", "genome")

MySQL.Connection(host="genome-mysql.soe.ucsc.edu", user="genome", port="3306", db="")

In [4]:
# Query the server and store the query in a dataframe - or a csv etc. 
result = DBInterface.execute(ucscDB, "show databases") |> DataFrame; 

In [5]:
# Lets view the result - we can see that it lists all the genomes stored on UCSC
result

340×1 DataFrame
 Row │ Database 
     │ String   
─────┼──────────
   1 │ acaChl1
   2 │ ailMel1
   3 │ allMis1
   4 │ allSin1
   5 │ amaVit1
   6 │ anaPla1
   7 │ ancCey1
   8 │ angJap1
   9 │ anoCar1
  10 │ anoCar2
  11 │ anoGam1
  ⋮  │    ⋮
 331 │ visiGene
 332 │ wuhCor1
 333 │ xenLae2
 334 │ xenTro1
 335 │ xenTro10
 336 │ xenTro2
 337 │ xenTro3
 338 │ xenTro7
 339 │ xenTro9
 340 │ zonAlb1
319 rows omitted

In [6]:
"hg38" in result.Database 

true

In [7]:
# Close the connection stream 
DBInterface.close!(ucscDB)

### Now that we've connected to the MySQL server, we will connect to a specific database and perform some queries. 

In R - we'll connect, retrieve all of the table associated with the db, and then execute a funtion to see how many table are stored 
```R
hg38 <- dbConnect(MySQL(), user="genome", db="hg38", host="genome-mysql.soe.ucsc.edu")
allTables <- dbListTables(hg38)
length(allTables)
```

Let's get cracking on Julia

In [8]:
hg38 = DBInterface.connect(MySQL.Connection, "genome-mysql.soe.ucsc.edu", "genome", db="hg38")

MySQL.Connection(host="genome-mysql.soe.ucsc.edu", user="genome", port="3306", db="hg38")

In [9]:
hg38Tables = DBInterface.execute(hg38, "show tables") |> DataFrame; 

In [10]:
hg38Tables[1:10, :]

10×1 DataFrame
 Row │ Tables_in_hg38      
     │ String              
─────┼─────────────────────
   1 │ affyGnf1h
   2 │ affyU133
   3 │ affyU95
   4 │ all_est
   5 │ all_mrna
   6 │ all_sts_primer
   7 │ all_sts_seq
   8 │ altLocations
   9 │ altSeqLiftOverPsl
  10 │ altSeqLiftOverPslP3

A whopping 2835 different tables ! UCSC is extreeeeemly information rich, as we can see, there are many many many data sources we can pull from.    

### Now to investigate the specific fields within a specific table

In R; get a table and perform a basic SQL function to show how many fields are in the table
```R
dbListFields(hg38, "all_mrna")
dbGetQuery(hg38, "select count(*) from all_mrna")
```

In Julia

In [11]:
countsql = DBInterface.execute(hg38, "select count(*) from all_mrna") |> DataFrame; 

In [12]:
countsql

1×1 DataFrame
 Row │ count(*) 
     │ Int64    
─────┼──────────
   1 │ 10489979

Now lets play with the contents of the fields in R

```R
mrnaData <- dbReadTable(hg38, "all_mrna")
head(mrnaData)
```

Julia !

In [30]:
mrnaData = DBInterface.execute(hg38, "select * from all_mrna;") |> DataFrame

10489979×22 DataFrame
      Row │ bin     matches  misMatches  repMatches  nCount  qNumInsert  qBase ⋯
          │ UInt16  UInt32   UInt32      UInt32      UInt32  UInt32      UInt3 ⋯
──────────┼─────────────────────────────────────────────────────────────────────
        1 │    585     1579          25           0       0           0        ⋯
        2 │    585     1419          21           0       0           0
        3 │    585     1533          12           0       0           0
        4 │    585     1578          27           0       0           0
        5 │    585     1652           0           0       0           0        ⋯
        6 │    585     1650           2           0       0           0
        7 │    585     1648           4           0       0           0
        8 │    585     1485           3           0       0           0
        9 │    585     1631           8           0       0           0        ⋯
       10 │    585     1736           4           0       0           0
       11 │    585      402           0           0       0           0
    ⋮     │   ⋮        ⋮         ⋮           ⋮         ⋮         ⋮             ⋱
 10489970 │    586      287           0           0       0           0
 10489971 │    586      285           0           0       0           0        ⋯
 10489972 │    586      279          10           0       0           0
 10489973 │    586      285           1           0       0           0
 10489974 │    586      284           2           0       0           0
 10489975 │    587      298           4           0       0           0        ⋯
 10489976 │    587      272           4           0       0           0
 10489977 │    588      280           7           0       0           0
 10489978 │    588      283           3           0       0           0
 10489979 │    703     2427           0           0       0           0        ⋯
                                            16 columns and 10489958 rows omitted

In [27]:
DataFrame(mrnaData, mrnaData[:, 1]) 

LoadError: MethodError: no method matching getindex(::MySQL.TextCursor{true}, ::Colon, ::Int64)

In [29]:
Pkg.add("CSV") ; using CSV

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


### Refined queries 
MySQL has a wide range of query options which permit the extration of virtually any aspect of the data, with conditionals, ranges, mismatches and so on. These statements must simply be crafted according to the query structure and provided to the julia functions in order to get what you're looking for.    

For instance we can extract entries from the table which have values in the 'mismatches' column between 1 and 3;   

In R
```R
query <- dbSendQuery(hg38, "select * from all_mrna where misMatches between 1 and 3") 
mrnas <- fetch(query)
```

In Julia

In [32]:
query = DBInterface.execute(hg38, "select * from all_mrna where misMatches between 1 and 3") |> DataFrame

403833×22 DataFrame
    Row │ bin     matches  misMatches  repMatches  nCount  qNumInsert  qBaseIn ⋯
        │ UInt16  UInt32   UInt32      UInt32      UInt32  UInt32      UInt32  ⋯
────────┼───────────────────────────────────────────────────────────────────────
      1 │    585     1650           2           0       0           0          ⋯
      2 │    585     1485           3           0       0           0
      3 │    585      925           2           0       0           1
      4 │    585      986           1           0       0           0
      5 │    585      970           3           0       0           0          ⋯
      6 │    585      953           2           0       0           0
      7 │    585      775           1           0       0           0
      8 │    585      974           2           0       0           0
      9 │    585     1123           1           0       0           0          ⋯
     10 │    585     1122           2           0       0           0
     11 │    586     1381           1           0       0           0
   ⋮    │   ⋮        ⋮         ⋮           ⋮         ⋮         ⋮            ⋮  ⋱
 403824 │    755      292           3           0       0           0
 403825 │     94      321           3           0       0           0          ⋯
 403826 │     94      319           3           0       0           0
 403827 │    585      294           2           0       0           0
 403828 │    585      292           3           0       0           0
 403829 │    585      294           3           0       0           0          ⋯
 403830 │    585      284           3           0       0           0
 403831 │    586      285           1           0       0           0
 403832 │    586      284           2           0       0           0
 403833 │    588      283           3           0       0           0          ⋯
                                              16 columns and 403812 rows omitted

In [34]:
first(query)

DataFrameRow
 Row │ bin     matches  misMatches  repMatches  nCount  qNumInsert  qBaseInser ⋯
     │ UInt16  UInt32   UInt32      UInt32      UInt32  UInt32      UInt32     ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │    585     1650           2           0       0           0             ⋯
                                                              16 columns omitted

In [ ]:
size(query)

### Close the connection!

In [37]:
DBInterface.close!(hg38)

## HDF5 - Reading and Handling this data type
HDF5 is a data format used for storing large datasets - FAST5 uses a HDF5 backbone, and we know how large FAST5 files are!!! It stands for **H**eirarchical **D**ata **F**ormat. 

As expected, HDF5 support for R comes in a library, this time it is downloaded from bioconductor 
```R
source("url")
biocLite("rhdf5")
library(rhdf5)
```

We can create an example file using the hdf5 functions `created = h5createFile("example.h5")`    

Julia too has a package for working with HDF5 formats, can you guess the original name? **HDF5.jl**. Remarkable indeed. https://juliaio.github.io/HDF5.jl/stable/ - A nice explaner of HDF5 from the julia software page 

*"HDF5 stands for Hierarchical Data Format v5 and is closely modeled on file systems. In HDF5, a "group" is analogous to a directory, a "dataset" is like a file. HDF5 also uses "attributes" to associate metadata with a particular group or dataset. HDF5 uses ASCII names for these different objects, and objects can be accessed by Unix-like pathnames, e.g., "/sample1/tempsensor/firsttrial" for a top-level group "sample1", a subgroup "tempsensor", and a dataset "firsttrial"."*  

(Datasets cannot have child datasets, but groups can have either.) 

Groups/subgroups/datasets NOT Groups/datasets/datasets/groups

In [39]:
Pkg.add("HDF5") ; using HDF5

   Resolving package versions...
   Installed MPIPreferences ─ v0.1.10
   Installed HDF5_jll ─────── v1.12.2+2
   Installed Requires ─────── v1.3.0
   Installed HDF5 ─────────── v0.17.1
    Updating `~/.julia/environments/v1.10/Project.toml`
  [f67ccb44] + HDF5 v0.17.1
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [f67ccb44] + HDF5 v0.17.1
  [3da0fdf6] + MPIPreferences v0.1.10
  [ae029012] + Requires v1.3.0
⌃ [0234f1f7] + HDF5_jll v1.12.2+2
        Info Packages marked with ⌃ have new versions available and may be upgradable.
Precompiling project...
  ✓ MPIPreferences
  ✓ Requires
  ✓ HDF5_jll
  ✓ HDF5
  4 dependencies successfully precompiled in 10 seconds. 60 already precompiled.


To write an example file in julia

In [41]:
example_hd = h5open("example.h5", "cw")

🗂️ HDF5.File: (read-write) example.h5

In [43]:
close(example_hd)

In [45]:
example_hd = h5open("example.h5", "r+")

🗂️ HDF5.File: (read-write) example.h5

Since HDF5 files are hierarchical and based upon a file-system like structure, we create groups

Once we have groups, we write to the groups, and perhaps subgroups, subsubgroups etc. - remember, HDF5 is akin to a filesystem

We'll create some matrix data which we'll write to a group called foo/A in R
```R
A = matrix(1:10, nr=5, nc=2)
h5write(A, "example.h5", "foo/A") #group is the third argument
B = array(seq(0.1,2.0, by=0.1), dim=c(5,2,2))
attr(B, "scale") <- "liter"
h5write(B, "example.h5", "foo/foobaa/B") 
h5ls("example.h5") # h5 ls view 
```

![image.png](attachment:image.png)

In Julia let's work with the HDF5 package 

Create a group called "foo" 

In [46]:
create_group(example_hd, "foo")

📂 HDF5.Group: /foo (file: example.h5)

Create some mock data

In [49]:
samp = Array(rand(2, 4))

2×4 Matrix{Float64}:
 0.453924  0.774484  0.896302  0.714723
 0.141766  0.911775  0.745648  0.932475

Write it to the group foo

In [51]:
# If a group doesn't already exist we can write to it by indexing
example_hd["newgroup"] = "yes"

"yes"

In [66]:
# To write to a pre-existing group 
# First initialize the group and load it into a variable
g = example_hd["foo"]
# Write to it by indexing directly
g["mydataset"] = samp 
# Write to it using the create_dataset() function
create_dataset(g, "simplestring", zeros(1, 2)) 

(HDF5.Dataset: /foo/simplestring (file: example.h5 xfer_mode: 0), HDF5.Datatype: H5T_IEEE_F64LE)

In [60]:
example_hd["foo/mydataset"]

🔢 HDF5.Dataset: /foo/mydataset (file: example.h5 xfer_mode: 0)

Read the contents of the dataset and its groups using the **read** function

In [61]:
read(example_hd["foo/mydataset"])

2×4 Matrix{Float64}:
 0.453924  0.774484  0.896302  0.714723
 0.141766  0.911775  0.745648  0.932475

In [67]:
read(example_hd["foo/simplestring"])

1×2 Matrix{Float64}:
 0.0  0.0

In [68]:
example_hd

🗂️ HDF5.File: (read-write) example.h5
├─ 📂 foo
│  ├─ 🔢 mydataset
│  └─ 🔢 simplestring
└─ 🔢 newgroup

In [71]:
close(example_hd)

For convience and consistency we can also use the **do** block conventions, which will take care of closing the stream for us 

In [73]:
h5open("example.h5", "r+") do stream
    group = create_group(stream, "dogroup")
    dataset = create_dataset(group, "thisdata", Float64, (10,10))
    write(dataset, rand(10,10))
end 

Basic notes;
Datasets can be create by 
```julia
g["mydataset"] = rand(3,5)
# or
write(g, "mydataset", rand(3,5))
``` 

### Reading specific parts of the data 
In R; 
```R
h5read("example.h5", "foo/A")
h5read("example.h5", "foo/new/dataset")
```

In Julia

In [89]:
openh5 = h5open("example.h5", "r+")

🗂️ HDF5.File: (read-write) example.h5
├─ 📂 dogroup
│  └─ 🔢 thisdata
├─ 📂 foo
│  ├─ 🔢 mydataset
│  └─ 🔢 simplestring
└─ 🔢 newgroup

In [91]:
read(openh5,"foo/mydataset")

2×4 Matrix{Float64}:
 0.453924  0.774484  0.896302  0.714723
 0.141766  0.911775  0.745648  0.932475

### Chunking and Compression 
The section on the Julia HDF5.jl package site does a nice job of explaining this ! https://juliaio.github.io/HDF5.jl/stable/

## Webscraping HTML 
Scraping information from the internet is a fun endevour, which based upon the virility of ones creativity, can lead to a large number of exciting avenues of adventure. As the web has been around for decades, almost every high level programming language has its own packages and libraries for working with web HTML and XML files. 
The most important part of web scraping is to avoid excessive request to websites as this will likely get your IP address blocked. We can safely assume that large companies such as amazon are interested in protecting themselves from massive data trawling operations, even though they are doing it on a massive scale. 

### Examples using google scholar

In R first; 

We'll store a url link, and then simply read the lines of the link, and then close the link 
```R
con = url("https://scholar.google.com/citations?user=kzht3-0AAAAJ&hl=en")
htmlCode = readLines(con)
close(con)
htmlCode
```

Now in Julia - we can use the HTTP.jl package - or Requests.jl

In [105]:
Pkg.add("HTTP") ; using HTTP

   Resolving package versions...
   Installed ExceptionUnwrapping ─ v0.1.10
   Installed SimpleBufferStream ── v1.1.0
   Installed ConcurrentUtilities ─ v2.3.0
   Installed BitFlags ──────────── v0.1.8
   Installed OpenSSL ───────────── v1.4.1
   Installed LoggingExtras ─────── v1.0.3
   Installed URIs ──────────────── v1.5.1
   Installed HTTP ──────────────── v1.10.1
    Updating `~/.julia/environments/v1.10/Project.toml`
  [cd3eb016] + HTTP v1.10.1
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [d1d4a3ce] + BitFlags v0.1.8
  [f0e56b4a] + ConcurrentUtilities v2.3.0
  [460bff9d] + ExceptionUnwrapping v0.1.10
  [cd3eb016] + HTTP v1.10.1
  [e6f89c97] + LoggingExtras v1.0.3
  [4d8831e6] + OpenSSL v1.4.1
  [777ac1f9] + SimpleBufferStream v1.1.0
  [5c2747f8] + URIs v1.5.1
Precompiling project...
  ✓ BitFlags
  ✓ SimpleBufferStream
  ✓ ExceptionUnwrapping
  ✓ LoggingExtras
  ✓ URIs
  ✓ ConcurrentUtilities
  ✓ OpenSSL
  ✓ HTTP
  8 dependencies successfully precompiled in 7 seconds

In [94]:
url = "https://scholar.google.com/citations?user=kzht3-0AAAAJ&hl=en"

"https://scholar.google.com/citations?user=kzht3-0AAAAJ&hl=en"

In [113]:
resp = HTTP.get(url)

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Wed, 31 Jan 2024 02:32:23 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Content-Type: text/html; charset=ISO-8859-1
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Server: citations
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Transfer-Encoding: chunked

<!doctype html><html><head><title>Michael Lynch - Google Scholar</title><meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="referrer" content="always"><meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=2"><meta name="format-detection" content="telephone=no"><link rel="shortcut icon" href="/favicon.ico"><link rel="canonical" href="https://scholar.google.com/citations?user=kzht3-0AAAAJ&amp;hl=en"><meta name="description" content="Arizona State

#### A note on GET vs POST requests
**GET**
* parameters are in the URL
* used for fetching and *GETTING* documents
* maximum URL length 
* OK to cache
* won't change the server

**POST**
* parameters are in the body
* used for updating and *POSTING* data 
* not ok to cache
* can change the server

#### Parsing HTML file as a XML - conversion 
Depending on the structure of the HTML, we may be able to translate it as a XML and interpret it in the same structure - let's give it a go and see if it works. 

In R; 
```R
library(XML)
url <- "https://scholar.google.com/citations?user=kzht3-0AAAAJ&hl=en"
html <- htmlTreeParse(url, useInternalNodes=T)
```
Using xpath language queries

```R
xpathSApply(html, "//title", xmlValue)
```

Now let's look at the citation counts
```R
xpathSApply(html, "//td[@id='col-citedby']", xmlValue)
``` 

Give it a crack in Julia using the EzXML package - it will take a few more steps, and perhaps it can get compressed down with experience into some simpler code.

**The basic steps are**
1. Load HTTP package, perform a HTTP get request on the url
2. Parse the URL as a string by accessing the requests body 
3. Using the EzXML package, parse the html string using parsehtml()
4. Use the xpath query language with findall() and nodecontent() to extract the relevant information from the file


In [114]:
Pkg.add("EzXML") ; using EzXML

   Resolving package versions...
   Installed XML2_jll ─ v2.12.2+0
   Installed EzXML ──── v1.2.0
    Updating `~/.julia/environments/v1.10/Project.toml`
  [8f5d6c58] + EzXML v1.2.0
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [8f5d6c58] + EzXML v1.2.0
  [02c8fc9c] + XML2_jll v2.12.2+0
Precompiling project...
  ✓ XML2_jll
  ✓ EzXML
  2 dependencies successfully precompiled in 2 seconds. 72 already precompiled.


Open a HTTP request, and then parse the HTML file as a string which can be read by the EzXML package using the **parsehtml()** function. 

In [144]:
samp = HTTP.get(url, cookies=true);
data = String(samp.body)

"<!doctype html><html><head><title>Michael Lynch - Google Scholar</title><meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"><meta name=\"referrer\" content=\"always\"><meta name=\"viewport\" content=\"wid" ⋯ 151840 bytes ⋯ "le=\"menuitem\" href=\"/intl/en/scholar/about.html\" tabindex=\"-1\" class=\"gs_md_li\">About Scholar</a><a role=\"menuitem\" href=\"//support.google.com/websearch?p=scholar_dsa&amp;hl=en&amp;oe=ASCII\" tabindex=\"-1\" class=\"gs_md_li\">Search help</a></div></div></div></body></html>"

Parse the html file now and store the root as a variable

In [154]:
q = parsehtml(data)
scholar_root = root(q)

┌ Warning: XMLError: Unexpected end tag : div from HTML parser (code: 76, line: 37)
└ @ EzXML ~/.julia/packages/EzXML/DL8na/src/error.jl:97
┌ Warning: XMLError: Unexpected end tag : div from HTML parser (code: 76, line: 41)
└ @ EzXML ~/.julia/packages/EzXML/DL8na/src/error.jl:97
┌ Warning: XMLError: Unexpected end tag : div from HTML parser (code: 76, line: 41)
└ @ EzXML ~/.julia/packages/EzXML/DL8na/src/error.jl:97
┌ Warning: XMLError: htmlParseEntityRef: expecting ';' from HTML parser (code: 23, line: 75)
└ @ EzXML ~/.julia/packages/EzXML/DL8na/src/error.jl:97
┌ Warning: XMLError: htmlParseEntityRef: expecting ';' from HTML parser (code: 23, line: 75)
└ @ EzXML ~/.julia/packages/EzXML/DL8na/src/error.jl:97
┌ Warning: XMLError: htmlParseEntityRef: expecting ';' from HTML parser (code: 23, line: 75)
└ @ EzXML ~/.julia/packages/EzXML/DL8na/src/error.jl:97


EzXML.Node(<ELEMENT_NODE[html]@0x0000000005486f00>)

Using the **nodecontent.()** function of EzXML, find your query using the xpath language 

In [160]:
nodecontent.(findall("//title", scholar_root))

1-element Vector{String}:
 "Michael Lynch - Google Scholar"

Now for the more elaborate Xpath query

In [164]:
for citation in nodecontent.(findall("//td[@id='col-citedby']", scholar_root))
    println(citation)
end 

#### Using the httr library for R 
httr makes doing much of this a bit easier - as we can see the workflow is very similar to that of HTTP.jl 
```R
library(httr); html2 = GET(url)
content2 = content(html2, as="text")
parsedHtml = htmlParse(content2, asText=True)
xpathSapply(parsedHtml, "//title", xmlValue)
```

### Websites with user and password authentication
In order to access websites which request a user and password, in R we can include the information as an argument
```R
pp2 = GET("url", authenticate("user","passwd"))
```

In Julia we prefix the server address as such;

In [168]:
pp2 = HTTP.get("https://user:passwd@httpbin.org/basic-auth/user/passwd")

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Thu, 01 Feb 2024 02:37:55 GMT
Content-Type: application/json
Content-Length: 47
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "authenticated": true, 
  "user": "user"
}
"""